### ISSUE TITLE
Broken link to rgbd-correction-mini.zip

### ISSUE THREAD

**Issue by pedro-patlan** [cheind/rgbd-correction#1]
Hi, 

I wanted to try your great project, but I ran into the broken link to `rgbd-correction-mini.zip`.  I will appreciate if you can provide this file.

Best,

Pedro

**Comment by cheind** [comment]
Hey Pedro,

interesting... I will investigate.

**Comment by pedro-patlan** [comment]
Thank you!

**Comment by kuwan2e** [comment]
@pedro-patlan Hi
It seems that we still can't get the dataset yet.

**Comment by cheind** [comment]
@kuwan2e I can confirm the link is dead. the associated AWS user for the storage was deleted and so was all the data with it. however, I believe I can recover the data from other sources, but this will take me a bit of time (maybe I have it done in 2 days).

**Comment by cheind** [comment]
The new files are hosted at zenodo:

https://zenodo.org/record/6827435#.Ys7SkXZBwuV

Both zip's maybe downloaded individually. I've recreated those files from local files, so I hope everything is included

**Comment by cheind** [comment]
I've also updated the readme with new direct links. Closing this - feel free to reopen if you have any troubles.
